version: '3'
services:
  web:
    image: "docker-test:${TAG}"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123456
      - SPRING_PROPERTIES=-Dspring.datasource.url=jdbc:postgresql://postgres/test -Dspring.datasource.username=test -Dspring.datasource.password=123456
    command: ["./wait-for-postgres.sh", "postgres:5432", "--", "catalina.sh", "run"]
  postgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=test